### ISSUE TITLE
geiger counters Radiation D v1.1 Cajoe with J305 tube

### ISSUE THREAD

**Issue by codystoica** [iotdevicesdev/ggreg20-v3-tasmota-esp32-driver#2]
Hello
I followed the steps described in this project but it does not calculate my radiation value.

Can you adapt this project for my setup?:
- Tasmota on nodemcu esp32 hw-463
- counter pulse on GPIO36
- geiger counters Radiation D v1.1 Cajoe with J305 tube
  I want to implement the values obtained in Domoticz
Thank you!
![geiger counter](https://user-images.githubusercontent.com/77228515/218310550-f1a1f285-57f7-481a-8488-17184dd8f678.png)

**Comment by iotdevicesdev** [comment]
Dear @codystoica 
Thank you for your question! 

This repo is intended for the [GGreg20_V3 Geiger Counter module](https://iot-devices.com.ua/en/product/ggreg20_v3-ionizing-radiation-detector-with-geiger-tube-sbm-20/) manufactured by our company.  As we can see, your setup is based on another radiation sensor module, thus to try to adopt our software example to your module, we need at least to have same module in our dev lab. But, as this example is licensed on an open source terms and conditions, you also may try to fork and adopt it to your own hardware and share it with others. Best regards, Team IoT-devices, LLC
